DROP TABLE Task;

CREATE TABLE Task
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(128) NOT NULL,
    description varchar(256),
    priority    int          NOT NULL,
    completed   BOOLEAN      NOT NULL,
    create_date timestamp    NOT NULL,
    finish_date timestamp
);